const images = {
	home_icon: require("../img/home_icon.png"),
	group_icon: require("../img/group_icon.png"),
	camera_icon: require("../img/camera_icon.png"),
	explore_icon: require("../img/explore_off.png"),
	heart_icon: require("../img/heart_icon.png"),
	notification_icon: require("../img/notification_icon.png"),
	profile_icon: require("../img/profile_icon.png"),
	home_icon_active: require("../img/home_icon_selected.png"),
	group_icon_active: require("../img/group_icon_selected.png"),
	camera_icon_active: require("../img/camera_icon_selected.png"),
	explore_icon_active: require("../img/explore_on.png"),
	heart_icon_active: require("../img/heart_icon_selected.png"),
	notification_icon_active: require("../img/notification_icon_selected.png"),
	profile_icon_active: require("../img/profile_icon_selected.png"),
	logo_high_res: require("../img/puff_logo_clear_background.png"),
	logo: require("../img/puff_logo_low_res.jpg"),
	couch: require("../img/stay_in_couch_icon.png"),
	smoke: require("../img/smoke.png"),
	movie: require("../img/tv_icon.png"),
	food: require("../img/food.png"),
	outdoors: require("../img/outdoor.png"),
	back: require("../img/grey_arrow.png"),
	back_white: require("../img/white_back_arrow.png"),
	back_new: require("../img/back.png"),
	rounded_checkmark: require("../img/rounded_checkmark.png"),

	circle_back: require("../img/circle_back.png"),
	circle_chat: require("../img/circle_chat.png"),
	circle_flag: require("../img/circle_flag.png"),
	photo_plus: require("../img/photo_plus.png"),

	puffy_letter: require("../img/puffy_letter.png"),
	puffy_logo: require("../img/puffy_logo.png"),
	logo_white: require("../img/logo_white.png"),

	man_off: require("../img/man_off.png"),
	man_on: require("../img/man_on.png"),
	woman_off: require("../img/woman_off.png"),
	woman_on: require("../img/woman_on.png"),
	back_arrow: require("../img/back_arrow.png"),
	checkmark_button: require("../img/checkmark_button.png"),
	search_icon_white: require("../img/search_icon_white.png"),

	arrow_down: require("../img/arrow_down.png"),

	ticket_off: require("../img/ticket_off.png"),
	ticket_on: require("../img/ticket_on.png"),
	ticket_plus: require("../img/ticket_plus.png"),

	edit_photo: require("../img/edit_photo.png"),
	puff_person: require("../img/puff_person.png"),
	puff: require("../img/puff.png"),

	video_off: require("../img/video_off.png"),
	photo_grey: require("../img/photo_grey.png"),
	photo_off: require("../img/photo_off.png"),
	photo_on: require("../img/photo_on.png"),
	video_on: require("../img/video_on.png"),

	camera_plus: require("../img/camera_plus.png"),
	back2: require("../img/back2.png"),
	circles_3: require("../img/3_circles.png"),

	white_add_photo_button: require("../img/white_add_photo_button.png"),
	white_puff_button: require("../img/white_puff_button.png"),
	white_setting_button: require("../img/white_setting_button.png"),
	white_ticket_button: require("../img/white_ticket_button.png"),
	white_plane_button: require("../img/message_icon_new.png"),

	message_icon_new: require("../img/message_icon_new.png"),

	up: require("../img/grey_arrow_scroll_up.png"),
	down: require("../img/grey_arrow_scroll_down.png"),
	green_circle: require("../img/green_circle_indicator.png"),
	settings: require("../img/settings_icon.png"),
	lock_icon: require("../img/lock_icon.png"),
	email_icon: require("../img/email_icon.png"),
	verify_key: require("../img/verify_key.png"),
	about_icon: require("../img/about_icon.png"),
	gender_icon_2: require("../img/gender_icon_2.png"),
	profile_info: require("../img/profile_info.png"),
	forgot_password_bg: require("../img/forgot_password_background.jpg"),
	login_bg: require("../img/log_in_background.jpg"),
	puffy_text: require("../img/puffy_text_icon.png"),
	birthday_icon: require("../img/bday_cake.png"),
	location_icon: require("../img/location_1.png"),
	drop_down: require("../img/drop_down_arrow.png"),
	dots3: require("../img/3_dots.png"),
	triple_circle: require("../img/triple_circle.png"),
	photoBtn: require("../img/take_photo_icon.png"),
	pencil_edit_icon: require("../img/pencil_edit_icon.png"),
	ic_camera_front_white: require("../img/ic_camera_front_white.png"),
	ic_camera_rear_white: require("../img/ic_camera_rear_white.png"),
	ic_flash_auto_white: require("../img/ic_flash_auto_white.png"),
	ic_flash_off_white: require("../img/ic_flash_off_white.png"),
	ic_flash_on_white: require("../img/ic_flash_on_white.png"),
	flip_cam_white: require("../img/flip_cam_white.png"),
	flash_icon_white: require("../img/flash_icon_white.png"),
	no_flash_icon_white: require("../img/no_flash_icon_white.png"),
	star_icon: require("../img/star_icon.png"),
	pencil: require("../img/pencil_edit_icon.png"),
	search_icon: require("../img/search_icon.png"),
	grey_messaging_airplane: require("../img/grey_messaging_airplane.png"),
	grey_messaging_airplane_red: require("../img/grey_messaging_airplane_red.png"),
	close_out_x_icon: require("../img/close_out_x.png"),
	gender_icon: require("../img/gender_icon.png"),
	message_friend: require("../img/message_friend.png"),
	galleryBtn: require("../img/gallery_button.png"),
	save_check: require("../img/save_check.png"),
	add_photo_icon: require("../img/addPhotoIcon.png"),

	smoke: require("../img/smoke.png"),
	smoke_on: require("../img/smoke_on.png"),
	smoke_white: require("../img/SMOKE_WHITE.png"),
	smoke_shadow: require("../img/SMOKE_SHADOW.png"),
	smoke_black: require("../img/SMOKE_BLACK.png"),
	smoke_green: require("../img/SMOKE_GREEN.png"),
	circle_smoke_on: require("../img/circlePref/circle_smoke_on.png"),
	circle_smoke_off: require("../img/circlePref/circle_smoke_off.png"),

	vape: require("../img/vape.png"),
	vape_on: require("../img/vape_on.png"),
	vape_white: require("../img/VAPE_WHITE.png"),
	vape_shadow: require("../img/VAPE_SHADOW.png"),
	vape_black: require("../img/VAPE_BLACK.png"),
	vape_green: require("../img/VAPE_GREEN.png"),
	circle_vape_on: require("../img/circlePref/circle_vape_on.png"),
	circle_vape_off: require("../img/circlePref/circle_vape_off.png"),

	edibles: require("../img/edibles.png"),
	edibles_on: require("../img/edibles_on.png"),
	edibles_white: require("../img/EDIBLE_WHITE.png"),
	edibles_shadow: require("../img/EDIBLES_SHADOW.png"),
	edibles_black: require("../img/EDIBLES_BLACK.png"),
	edibles_green: require("../img/EDIBLES_GREEN.png"),
	circle_edibles_on: require("../img/circlePref/circle_edibles_on.png"),
	circle_edibles_off: require("../img/circlePref/circle_edibles_off.png"),

	chill: require("../img/chill.png"),
	chill_on: require("../img/chill_on.png"),
	chill_white: require("../img/CHILL_WHITE.png"),
	chill_shadow: require("../img/CHILL_SHADOW.png"),
	chill_black: require("../img/CHILL_BLACK.png"),
	chill_green: require("../img/CHILL_GREEN.png"),
	circle_chill_on: require("../img/circlePref/circle_chill_on.png"),
	circle_chill_off: require("../img/circlePref/circle_chill_off.png"),

	outdoor: require("../img/outdoor.png"),
	outdoor_on: require("../img/outdoor_on.png"),
	outdoor_white: require("../img/OUTDOR_WHITE.png"),
	outdoor_shadow: require("../img/OUTDOR_SHADOW.png"),
	outdoor_black: require("../img/OUTDOR_BLACK.png"),
	outdoor_green: require("../img/OUTDOR_GREEN.png"),
	circle_outdoor_on: require("../img/circlePref/circle_outdoor_on.png"),
	circle_outdoor_off: require("../img/circlePref/circle_outdoor_off.png"),

	flicks: require("../img/flicks.png"),
	flicks_on: require("../img/flicks_on.png"),
	flicks_white: require("../img/FLICK_WHITE.png"),
	flicks_shadow: require("../img/FLICKS_SHADOW.png"),
	flicks_black: require("../img/FLICKS_BLACK.png"),
	flicks_green: require("../img/FLICKS_GREEN.png"),
	circle_flicks_on: require("../img/circlePref/circle_flicks_on.png"),
	circle_flicks_off: require("../img/circlePref/circle_flicks_off.png"),

	games: require("../img/videogames.png"),
	games_on: require("../img/videogames_on.png"),
	games_white: require("../img/GAMES_WHITE.png"),
	games_shadow: require("../img/GAMES_SHADOW.png"),
	games_black: require("../img/GAMES_BLACK.png"),
	games_green: require("../img/GAMES_GREEN.png"),
	circle_games_on: require("../img/circlePref/circle_games_on.png"),
	circle_games_off: require("../img/circlePref/circle_games_off.png"),

	sports: require("../img/sports.png"),
	sports_on: require("../img/sports_on.png"),
	sports_white: require("../img/SPORT_WHITE.png"),
	sports_shadow: require("../img/SPORT_SHADOW.png"),
	sports_black: require("../img/SPORT_BLACK.png"),
	sports_green: require("../img/SPORT_GREEN.png"),
	circle_sports_on: require("../img/circlePref/circle_sports_on.png"),
	circle_sports_off: require("../img/circlePref/circle_sports_off.png"),

	clubs: require("../img/clubs.png"),
	clubs_on: require("../img/clubs_on.png"),
	clubs_white: require("../img/CLUB_WHITE.png"),
	clubs_shadow: require("../img/CLUB_SHADOW.png"),
	clubs_black: require("../img/CLUB_BLACK.png"),
	clubs_green: require("../img/CLUB_GREEN.png"),
	circle_clubs_on: require("../img/circlePref/circle_clubs_on.png"),
	circle_clubs_off: require("../img/circlePref/circle_clubs_off.png"),

	concert: require("../img/concert.png"),
	concert_on: require("../img/concert_on.png"),
	concert_white: require("../img/SHOW_WHITE.png"),
	concert_shadow: require("../img/SHOW_SHADOW.png"),
	concert_black: require("../img/SHOW_BLACK.png"),
	concert_green: require("../img/SHOW_GREEN.png"),
	circle_concert_on: require("../img/circlePref/circle_concert_on.png"),
	circle_concert_off: require("../img/circlePref/circle_concert_off.png"),

	food: require("../img/food.png"),
	food_on: require("../img/food_on.png"),
	food_white: require("../img/FOOD_WHITE.png"),
	food_shadow: require("../img/FOOD_SHADOW.png"),
	food_black: require("../img/FOOD_BLACK.png"),
	food_green: require("../img/FOOD_GREEN.png"),
	circle_food_on: require("../img/circlePref/circle_food_on.png"),
	circle_food_off: require("../img/circlePref/circle_food_off.png"),

	videogames: require("../img/games.png"),
	videogames_on: require("../img/games_on.png"),
	videogames_white: require("../img/CHAT_WHITE.png"),
	videogames_shadow: require("../img/CHAT_SHADOW.png"),
	videogames_black: require("../img/CHAT_BLACK.png"),
	videogames_green: require("../img/CHAT_GREEN.png"),
	circle_videogames_on: require("../img/circlePref/circle_chat_on.png"),
	circle_videogames_off: require("../img/circlePref/circle_chat_off.png"),

	friend: require("../img/friend.png"),
	friend_black: require("../img/FRIEND_BLACK.png"),
	friend_green: require("../img/FRIEND_GREEN.png"),
	friend_shadow: require("../img/FRIEND_SHADOW.png"),
	circle_friend_on: require("../img/circlePref/circle_friend_on.png"),
	circle_friend_off: require("../img/circlePref/circle_friend_off.png"),

	liquor: require("../img/liquor.png"),
	liquor_black: require("../img/LIQUOR_BLACK.png"),
	liquor_green: require("../img/LIQUOR_GREEN.png"),
	liquor_shadow: require("../img/LIQUOR_SHADOW.png"),
	circle_liquor_on: require("../img/circlePref/circle_liquor_on.png"),
	circle_liquor_off: require("../img/circlePref/circle_liquor_off.png"),

	love: require("../img/love.png"),
	love_black: require("../img/LOVE_BLACK.png"),
	love_green: require("../img/LOVE_GREEN.png"),
	love_shadow: require("../img/LOVE_SHADOW.png"),
	circle_love_on: require("../img/circlePref/circle_love_on.png"),
	circle_love_off: require("../img/circlePref/circle_love_off.png"),

	hotbox: require("../img/hotbox.png"),
	hotbox_black: require("../img/HOTBOX_BLACK.png"),
	hotbox_green: require("../img/HOTBOX_GREEN.png"),
	hotbox_shadow: require("../img/HOTBOX_SHADOW.png"),
	circle_hotbox_on: require("../img/circlePref/circle_hotbox_on.png"),
	circle_hotbox_off: require("../img/circlePref/circle_hotbox_off.png"),

	karaoke: require("../img/karaoke.png"),
	karaoke_black: require("../img/KARAOKE_BLACK.png"),
	karaoke_green: require("../img/KARAOKE_GREEN.png"),
	karaoke_shadow: require("../img/KARAOKE_SHADOW.png"),
	circle_karaoke_on: require("../img/circlePref/circle_karaoke_on.png"),
	circle_karaoke_off: require("../img/circlePref/circle_karaoke_off.png"),

	music: require("../img/music.png"),
	music_black: require("../img/MUSIC_BLACK.png"),
	music_green: require("../img/MUSIC_GREEN.png"),
	music_shadow: require("../img/MUSIC_SHADOW.png"),
	circle_music_on: require("../img/circlePref/circle_music_on.png"),
	circle_music_off: require("../img/circlePref/circle_music_off.png"),

	send_button: require("../img/send_button.png"),
	filter: require("../img/filter.png"),
	plus_sign: require("../img/plus.png"),
	check_mark: require("../img/checkmark.png"),
	x_icon: require("../img/x_icon.png"),
	read: require("../img/read.png"),
	ref: require("../img/ref.png"),

	star_none: require("../img/star_none.png"),
	star_one: require("../img/star_one.png"),
	star_one_half: require("../img/star_one_half.png"),
	star_two: require("../img/star_two.png"),
	star_two_half: require("../img/star_two.png"),
	star_three: require("../img/star_three.png"),
	star_three_half: require("../img/star_three_half.png"),
	star_four: require("../img/star_four.png"),
	star_four_half: require("../img/star_four_half.png"),
	star_five: require("../img/star_five.png"),
	arrow_right: require("../img/arrow_right.png"),
	dropdown_arrow: require("../img/dropdown_arrow.png"),

	logo: require("../img/logo.png"),

	locked_eye: require("../img/locked_eye.png"),
	love_off: require("../img/love_off.png"),
	love_on: require("../img/love_on.png"),
	loading: require("../img/loading.jpg"),
	neutral_big: require("../img/neutral_big.png"),
	medal: require("../img/medal.png"),

	empty_event: require("../img/empty_event.png"),
	edit_event: require("../img/edit_event.png"),
	pending_event: require("../img/pending_event.png"),
	confirmed_guest: require("../img/confirmed_guest.png"),

	medal_grey: require("../img/medal_grey.png"),
	medal_gold: require("../img/medal_gold.png"),

	plus_icon: require("../img/plus_icon.png"),
	checkmark: require("../img/checkmark.png"),
	medal_white: require("../img/medal_white.png"),

	gray_star: require("../img/gray_star.png"),
	gold_star: require("../img/gold_star.png"),
	binocular: require("../img/binocular.png"),
	puff_person_white: require("../img/puff_person_white.png"),
	pending: require("../img/pending.png"),
	event_calendar_off_plus: require("../img/event_calendar_off_plus.png"),
	explorer_off: require("../img/nav/explorer_off.png"),
	explorer_on: require("../img/nav/explorer_on.png"),

	polaroid_friend_off: require("../img/polaroid_friend_off.png"),
	polaroid_friend_on: require("../img/polaroid_friend_on.png"),

	polaroid_friends_off: require("../img/polaroid_friends_off.png"),
	polaroid_friends_on: require("../img/polaroid_friends_on.png"),

	polaroid_explorer_off: require("../img/polaroid_explorer_off.png"),
	polaroid_explorer_on: require("../img/polaroid_explorer_on.png"),
	passed: require("../img/passed.png"),
	puffed: require("../img/puffed.png"),

	passBtn: require("../img/passBtn.png"),
	puffBtn: require("../img/puffBtn.png"),
	puffBtn2: require("../img/puffBtn2.png"),
	passBtn3: require("../img/passBtn3.png"),
	puffBtn3: require("../img/puffBtn3.png"),
	passBtn5: require("../img/passbutton.png"),
	puffBtn5: require("../img/puffbutton.png"),

	puff_stamp: require("../img/puff_stamp.png"),
	pass_stamp: require("../img/pass_stamp.png"),

	puff_polaroid_off: require("../img/puff_polaroid_off.png"),
	puff_polaroid_on: require("../img/puff_polaroid_on.png"),
	event_calendar_on_plus_white: require("../img/event_calendar_on_plus_white.png"),
	fb_icon: require("../img/fb_icon.png"),
	red_flag: require("../img/red_flag.png"),

	men_green: require("../img/men_green.png"),
	men_grey: require("../img/men_grey.png"),
	women_grey: require("../img/women_grey.png"),
	women_pink: require("../img/women_pink.png"),
	slide1: require("../img/slide/slide1.png"),
	slide2: require("../img/slide/slide2.png"),
	slide3: require("../img/slide/slide3.png"),
	slide4: require("../img/slide/slide4.png"),
	vid: require("../img/vid.png"),
	contact: require("../img/contact.png")
};

export default images;
